const PRICING={minTicket:50,emptyKmRate:1,baseLoadedKmRate:1,maxLoadedKmRate:2,maxVolumeM3:15,maxWeightKg:2000,includedVolumeM3:5,includedWeightKg:200,handlingUnitKg:100,handlingUnitM3:3,handlingUnitPrice:20,handlingMaxPerOperation:50,floorUnitPrice:2.5,floorBlockSize:3};
const SCHEDULING={hourlyRate:60,travelKmPerHour:40,handlingVolumeUnitM3:2,handlingWeightUnitKg:50,handlingMinutesPerUnit:3,floorMinutesPerTrip:3,roundingMinutes:15};
const CONFIG=window.EBROMOVE_CONFIG||{};
const $=(id)=>document.querySelector(id);
const form=$("#quoteForm"),statusEl=$("#formStatus"),copyQuoteButton=$("#copyQuote"),reserveBookingButton=$("#reserveBooking"),whatsappLink=$("#whatsappLink"),calendarStatusEl=$("#calendarStatus"),bookingListEl=$("#bookingList"),calendarDownloadLink=$("#calendarDownload");
const fields={baseAddress:$("#baseAddress"),baseCity:$("#baseCity"),pickupAddress:$("#pickupAddress"),pickupCity:$("#pickupCity"),deliveryAddress:$("#deliveryAddress"),deliveryCity:$("#deliveryCity"),serviceAt:$("#serviceAt"),volume:$("#volume"),weight:$("#weight"),pickupFloors:$("#pickupFloors"),deliveryFloors:$("#deliveryFloors"),emptyKm:$("#emptyKm"),loadedKm:$("#loadedKm")};
const output={totalPrice:$("#totalPrice"),routeSummary:$("#routeSummary"),vehicleCount:$("#vehicleCount"),serviceAtOutput:$("#serviceAtOutput"),emptyCost:$("#emptyCost"),loadedCost:$("#loadedCost"),loadCost:$("#loadCost"),unloadCost:$("#unloadCost"),floorCost:$("#floorCost"),kmRate:$("#kmRate"),serviceDuration:$("#serviceDuration"),timeCost:$("#timeCost"),bookingStatus:$("#bookingStatus")};
let lastQuote=null,availabilityTimer=null;
function num(v,f=0){const n=Number.parseFloat(String(v||"").replace(",","."));return Number.isFinite(n)?n:f}
function clamp(v,min,max=Number.POSITIVE_INFINITY){return Math.min(Math.max(v,min),max)}
function money(v){const r=Number.isInteger(v)?v:Number(v.toFixed(2));return `${r.toLocaleString("es-ES",{maximumFractionDigits:2})} \u20ac`}
function km(v){return `${v.toLocaleString("es-ES",{maximumFractionDigits:1})} km`}
function minutes(v){const m=Math.round(v),h=Math.floor(m/60),r=m%60;return h&&r?`${h} h ${r} min`:h?`${h} h`:`${r} min`}
function fmtInput(d){const p=(v)=>String(v).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function setDefaultDate(){const now=new Date(),d=new Date(now.getTime()+3600000);d.setMinutes(Math.ceil(d.getMinutes()/30)*30,0,0);fields.serviceAt.min=fmtInput(now);if(!fields.serviceAt.value)fields.serviceAt.value=fmtInput(d)}
function fmtDate(v){if(!v)return"por confirmar";const d=new Date(v);return Number.isNaN(d.getTime())?"por confirmar":new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function range(start,end){const day=new Intl.DateTimeFormat("es-ES",{weekday:"short",day:"numeric",month:"short"}).format(start),time=new Intl.DateTimeFormat("es-ES",{hour:"2-digit",minute:"2-digit"});return `${day}, ${time.format(start)} - ${time.format(end)}`}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("es-ES").trim()}
function join(a,c){const aa=String(a||"").trim(),cc=String(c||"").trim();if(!aa)return cc;if(!cc||norm(aa).includes(norm(cc)))return aa;return `${aa}, ${cc}`}
function addr(a,c){return join(a,c)||"por confirmar"}
function apiUrl(){return String(CONFIG.bookingApiUrl||"").trim()}
function hasApi(){return /^https:\/\//i.test(apiUrl())}
function setReserveEnabled(v){if(reserveBookingButton)reserveBookingButton.disabled=!v}
function phone(){return String(CONFIG.whatsappPhone||"").replace(/\D/g,"")}
function whatsappHref(text){const p=phone(),e=encodeURIComponent(text);return p?`https://wa.me/${p}?text=${e}`:`https://wa.me/?text=${e}`}
function openWA(text){const href=whatsappHref(text),w=window.open(href,"_blank","noopener");if(!w)window.location.href=href}
function remoteUrl(action,params={}){const u=new URL(apiUrl());u.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,String(v))});return u}
function jsonp(url){return new Promise((resolve,reject)=>{const cb=`ebromoveJsonp_${Date.now()}_${Math.random().toString(36).slice(2)}`,s=document.createElement("script"),cleanup=()=>{clearTimeout(t);delete window[cb];s.remove()},t=setTimeout(()=>{cleanup();reject(new Error("La agenda conectada no ha respondido a tiempo."))},10000);window[cb]=(payload)=>{cleanup();payload?.error?reject(new Error(payload.error)):resolve(payload)};url.searchParams.set("callback",cb);s.async=true;s.src=url.toString();s.onerror=()=>{cleanup();reject(new Error("No he podido conectar con la agenda externa."))};document.head.append(s)})}
async function getRemote(action,params={}){if(!hasApi())throw new Error("Falta configurar la URL de Google Calendar.");const url=remoteUrl(action,params);return CONFIG.bookingApiUseJsonp!==false?jsonp(url):getJson(url,"No he podido conectar con la agenda externa.")}
async function postRemote(action,payload){if(!hasApi())throw new Error("Falta configurar la URL de Google Calendar.");const r=await fetch(remoteUrl(action).toString(),{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token:String(CONFIG.bookingToken||""),payload})}),text=await r.text();let data={};try{data=JSON.parse(text)}catch{throw new Error("La agenda externa ha respondido con un formato no valido.")}if(!r.ok||data.error)throw new Error(data.error||"No he podido guardar la reserva.");return data}
function loadShare(vol,wt){const cv=Math.max(0,vol-PRICING.includedVolumeM3),cw=wt>0?Math.max(0,wt-PRICING.includedWeightKg):0;return Math.max(clamp(cv/(PRICING.maxVolumeM3-PRICING.includedVolumeM3),0,1),wt>0?clamp(cw/(PRICING.maxWeightKg-PRICING.includedWeightKg),0,1):0)}
function chargeUnits(vol,wt){const cv=Math.max(0,vol-PRICING.includedVolumeM3),cw=wt>0?Math.max(0,wt-PRICING.includedWeightKg):0;return Math.max(cv>0?Math.ceil(cv/PRICING.handlingUnitM3):0,cw>0?Math.ceil(cw/PRICING.handlingUnitKg):0)}
function opFee(units){return units<=0?0:Math.min(PRICING.handlingMaxPerOperation,Math.max(PRICING.handlingUnitPrice,units*PRICING.handlingUnitPrice))}
function vehicles(vol,wt){return Math.max(1,Math.ceil(Math.max(vol,.1)/PRICING.maxVolumeM3),wt>0?Math.ceil(wt/PRICING.maxWeightKg):1)}
function vehicleLoads(vol,wt,count){let rv=Math.max(vol,0),rw=Math.max(wt,0);return Array.from({length:count},()=>{const v=Math.min(PRICING.maxVolumeM3,rv),w=wt>0?Math.min(PRICING.maxWeightKg,rw):0;rv=Math.max(0,rv-v);rw=Math.max(0,rw-w);return{vol:v,wt:w}})}
function loadedRate(vol,wt){return clamp(PRICING.baseLoadedKmRate*(1+loadShare(vol,wt)),PRICING.baseLoadedKmRate,PRICING.maxLoadedKmRate)}
function floorExtra(vol,wt,p,d){const estimated=wt>0?wt:vol/PRICING.maxVolumeM3*PRICING.maxWeightKg,units=Math.max(1,Math.ceil(estimated/PRICING.handlingUnitKg));return units*PRICING.floorUnitPrice*(Math.ceil(Math.max(p,0)/PRICING.floorBlockSize)+Math.ceil(Math.max(d,0)/PRICING.floorBlockSize))}
function workUnits(vol,wt){return Math.max(1,Math.ceil(Math.max(vol,.1)/SCHEDULING.handlingVolumeUnitM3),wt>0?Math.ceil(wt/SCHEDULING.handlingWeightUnitKg):0)}
function floorTrips(vol,wt){return wt>0?Math.max(1,Math.ceil(wt/SCHEDULING.handlingWeightUnitKg)):workUnits(vol,wt)}
function schedule(i,count){const travelKm=i.emptyKm+i.loadedKm*count,travelMinutes=travelKm/SCHEDULING.travelKmPerHour*60,units=workUnits(i.volumeM3,i.weightKg),trips=floorTrips(i.volumeM3,i.weightKg),pickupHandlingMinutes=units*SCHEDULING.handlingMinutesPerUnit,deliveryHandlingMinutes=pickupHandlingMinutes,pickupFloorMinutes=trips*Math.max(i.pickupFloors,0)*SCHEDULING.floorMinutesPerTrip,deliveryFloorMinutes=trips*Math.max(i.deliveryFloors,0)*SCHEDULING.floorMinutesPerTrip,rawMinutes=travelMinutes+pickupHandlingMinutes+deliveryHandlingMinutes+pickupFloorMinutes+deliveryFloorMinutes,roundedMinutes=Math.max(SCHEDULING.roundingMinutes,Math.round(rawMinutes/SCHEDULING.roundingMinutes)*SCHEDULING.roundingMinutes);return{travelKm,travelMinutes,handlingUnits:units,floorTrips:trips,pickupHandlingMinutes,deliveryHandlingMinutes,pickupFloorMinutes,deliveryFloorMinutes,rawMinutes,roundedMinutes,timeCost:roundedMinutes/60*SCHEDULING.hourlyRate}}
function calc(i){const count=vehicles(i.volumeM3,i.weightKg),loads=vehicleLoads(i.volumeM3,i.weightKg,count),rates=loads.map(l=>loadedRate(l.vol,l.wt)),rateTotal=rates.reduce((a,b)=>a+b,0),fees=loads.map(l=>opFee(chargeUnits(l.vol,l.wt))),loadFee=fees.reduce((a,b)=>a+b,0),unloadFee=loadFee,emptyCost=i.emptyKm*PRICING.emptyKmRate*count,loadedCost=i.loadedKm*rateTotal,floor=floorExtra(i.volumeM3,i.weightKg,i.pickupFloors,i.deliveryFloors),base=emptyCost+loadedCost+loadFee+unloadFee,sch=schedule(i,count),legacy=Math.max(PRICING.minTicket*count,base)+floor;return{...i,vehicleCount:count,loadedKmRates:rates,loadedKmRate:rateTotal/count,loadFee,unloadFee,floorExtra:floor,emptyCost,loadedCost,baseSubtotal:base,schedule:sch,timeCost:sch.timeCost,legacyTotal:legacy,total:Math.max(legacy,sch.timeCost)}}
function read(){return{emptyKm:Math.max(0,num(fields.emptyKm.value)),loadedKm:Math.max(0,num(fields.loadedKm.value)),volumeM3:Math.max(.1,num(fields.volume.value,3)),weightKg:Math.max(0,num(fields.weight.value)),pickupFloors:clamp(Math.round(num(fields.pickupFloors.value)),0,12),deliveryFloors:clamp(Math.round(num(fields.deliveryFloors.value)),0,12),serviceAt:fields.serviceAt.value}}
function quoteWindow(q){const s=new Date(q.serviceAt);if(!q.serviceAt||Number.isNaN(s.getTime()))return null;return{start:s,end:new Date(s.getTime()+q.schedule.roundedMinutes*60000)}}
function rateLabel(q){const min=Math.min(...q.loadedKmRates),max=Math.max(...q.loadedKmRates),fmt=(v)=>`${v.toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})} \u20ac/km`;return Math.abs(max-min)<.005?fmt(max):`${fmt(min)} - ${fmt(max)}`}
function message(q,intro="Hola Jairo, quiero confirmar este porte:"){const w=quoteWindow(q);return[intro,`Recogida: ${addr(fields.pickupAddress.value,fields.pickupCity.value)}`,`Entrega: ${addr(fields.deliveryAddress.value,fields.deliveryCity.value)}`,`Fecha y hora: ${fmtDate(q.serviceAt)}`,`Duraci\u00f3n bloqueada: ${minutes(q.schedule.roundedMinutes)}${w?` (${range(w.start,w.end)})`:""}`,`Volumen aproximado: ${q.volumeM3} m\u00b3`,q.weightKg>0?`Peso aproximado: ${q.weightKg} kg`:"Peso aproximado: por confirmar",`Furgonetas/viajes estimados: ${q.vehicleCount}`,`Plantas recogida: ${q.pickupFloors}`,`Plantas entrega: ${q.deliveryFloors}`,`Km hasta recogida: ${q.emptyKm.toFixed(1)}`,`Km con carga: ${q.loadedKm.toFixed(1)}`,`Precio por tiempo: ${money(q.timeCost)}`,`Estimaci\u00f3n: ${money(q.total)}`].join("\n")}
function render(q,src="manual"){lastQuote=q;output.totalPrice.textContent=money(q.total);output.vehicleCount.textContent=q.vehicleCount===1?"1 furgoneta":`${q.vehicleCount} furgonetas`;output.serviceAtOutput.textContent=fmtDate(q.serviceAt);output.emptyCost.textContent=`${money(q.emptyCost)} (${km(q.emptyKm)})`;output.loadedCost.textContent=`${money(q.loadedCost)} (${km(q.loadedKm)})`;output.loadCost.textContent=money(q.loadFee);output.unloadCost.textContent=money(q.unloadFee);output.floorCost.textContent=money(q.floorExtra);output.kmRate.textContent=rateLabel(q);output.serviceDuration.textContent=minutes(q.schedule.roundedMinutes);output.timeCost.textContent=money(q.timeCost);output.bookingStatus.textContent="Comprobando...";const w=quoteWindow(q),booking=w?`Bloque horario: ${range(w.start,w.end)}.`:"Bloque horario: por confirmar.";output.routeSummary.textContent=`${src==="map"?"Ruta calculada por carretera":"Kil\u00f3metros introducidos manualmente"}: ${km(q.emptyKm)} hasta la recogida y ${km(q.loadedKm)} con carga. Volumen: ${q.volumeM3.toLocaleString("es-ES")} m\u00b3${q.weightKg>0?`, peso: ${q.weightKg.toLocaleString("es-ES")} kg`:""}. Se estiman ${q.vehicleCount===1?"1 furgoneta/viaje":`${q.vehicleCount} furgonetas/viajes`}. ${booking}`;whatsappLink.href=whatsappHref(message(q));scheduleCheck()}
function setStatus(msg,type="info"){statusEl.textContent=msg;statusEl.classList.toggle("error",type==="error")}
function setCalStatus(msg,type="info"){if(!calendarStatusEl)return;calendarStatusEl.textContent=msg;calendarStatusEl.classList.toggle("error",type==="error");calendarStatusEl.classList.toggle("success",type==="success")}
function scheduleCheck(){clearTimeout(availabilityTimer);availabilityTimer=setTimeout(()=>checkAvailability(lastQuote),350)}
async function checkAvailability(q){if(!q)return;if(!hasApi()){output.bookingStatus.textContent="WhatsApp";setReserveEnabled(true);setCalStatus("Sin Google Calendar conectado: el bot\u00f3n enviar\u00e1 la solicitud por WhatsApp Business.");return}const w=quoteWindow(q);if(!w){output.bookingStatus.textContent="Sin fecha";setReserveEnabled(false);return}try{const p=await getRemote("availability",{startAt:w.start.toISOString(),durationMinutes:q.schedule.roundedMinutes});if(p.available){output.bookingStatus.textContent="Disponible";setReserveEnabled(true);return}if(p.conflict?.startAt&&p.conflict?.endAt){output.bookingStatus.textContent=`Ocupado: ${range(new Date(p.conflict.startAt),new Date(p.conflict.endAt))}`}else output.bookingStatus.textContent="Ocupado";setReserveEnabled(false)}catch(e){output.bookingStatus.textContent="Sin agenda";setReserveEnabled(false);setCalStatus(e.message||"No he podido comprobar la agenda.","error")}}
function payload(q){const w=quoteWindow(q);if(!w)throw new Error("Selecciona fecha y hora para bloquear el porte.");return{source:"website",publicSiteUrl:String(CONFIG.publicSiteUrl||window.location.href),startAt:w.start.toISOString(),endAt:w.end.toISOString(),durationMinutes:q.schedule.roundedMinutes,pickup:{address:fields.pickupAddress.value.trim(),city:fields.pickupCity.value.trim()},delivery:{address:fields.deliveryAddress.value.trim(),city:fields.deliveryCity.value.trim()},route:{emptyKm:q.emptyKm,loadedKm:q.loadedKm},load:{volumeM3:q.volumeM3,weightKg:q.weightKg,pickupFloors:q.pickupFloors,deliveryFloors:q.deliveryFloors,vehicleCount:q.vehicleCount},schedule:q.schedule,quote:{total:q.total,timeCost:q.timeCost,legacyTotal:q.legacyTotal,loadFee:q.loadFee,unloadFee:q.unloadFee,floorExtra:q.floorExtra}}}
function renderBookings(bookings){if(!bookingListEl)return;bookingListEl.textContent="";if(!bookings.length){const p=document.createElement("p");p.className="calendar-empty";p.textContent=hasApi()?"No hay portes reservados.":"Sin Google Calendar conectado; las solicitudes se env\u00edan por WhatsApp Business.";bookingListEl.append(p);return}bookings.forEach(b=>{const s=new Date(b.startAt),e=new Date(b.endAt),item=document.createElement("article");item.className="booking-item";const main=document.createElement("div"),title=document.createElement("strong"),route=document.createElement("span"),detail=document.createElement("small");title.textContent=`${range(s,e)} · ${money(Number(b.quote?.total||0))}`;route.textContent=`${addr(b.pickup?.address,b.pickup?.city)} -> ${addr(b.delivery?.address,b.delivery?.city)}`;detail.textContent=`${minutes(Number(b.durationMinutes||0))} · ${b.load?.volumeM3||0} m\u00b3 · ${Number(b.load?.weightKg||0)>0?`${b.load.weightKg} kg`:"peso pendiente"}`;main.append(title,route,detail);item.append(main);bookingListEl.append(item)})}
async function loadAgenda(){if(!hasApi()){renderBookings([]);setCalStatus("Sin Google Calendar conectado: las solicitudes se enviar\u00e1n por WhatsApp Business.");if(calendarDownloadLink)calendarDownloadLink.hidden=true;return}try{const p=await getRemote("bookings",{from:new Date().toISOString()});renderBookings(p.bookings||[]);setCalStatus("Agenda conectada con Google Calendar.","success");if(calendarDownloadLink&&CONFIG.calendarUrl){calendarDownloadLink.href=CONFIG.calendarUrl;calendarDownloadLink.target="_blank";calendarDownloadLink.rel="noopener";calendarDownloadLink.hidden=false}else if(calendarDownloadLink)calendarDownloadLink.hidden=true}catch(e){renderBookings([]);setCalStatus(e.message||"No he podido cargar la agenda.","error")}}
function validPoint(r){const lat=parseFloat(r.lat),lon=parseFloat(r.lon);return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=27&&lat<=44.5&&lon>=-19&&lon<=5}
function matchesCity(r,city){const c=norm(city);if(!c)return true;const a=r.address||{},t=norm(`${a.city||""} ${a.town||""} ${a.village||""} ${a.hamlet||""} ${a.municipality||""}`);return t.includes(c)}
function mapPhoton(f){const p=f.properties||{},[lon,lat]=f.geometry?.coordinates||[],street=[p.street,p.housenumber].filter(Boolean).join(" ");return{lat,lon,display_name:[p.name,street,p.postcode,p.city||p.county,p.state,p.country].filter(Boolean).join(", "),importance:.5,address:{road:p.street,house_number:p.housenumber,city:p.city,town:p.city,village:p.city,municipality:p.city||p.county,county:p.county,state:p.state,postcode:p.postcode,country:p.country,country_code:p.countrycode}}}
async function getJson(url,msg){let r;try{r=await fetch(url.toString(),{headers:{Accept:"application/json"}})}catch{throw new Error(msg)}if(!r.ok)throw new Error(msg);return r.json()}
async function geocode(address,city){const label=join(address,city);if(!label)throw new Error("Falta una direcci\u00f3n para calcular la ruta.");const sources=[async()=>{const u=new URL("https://www.cartociudad.es/geocoder/api/geocoder/candidates");u.searchParams.set("q",address||city);u.searchParams.set("limit","8");if(city)u.searchParams.set("municipio_filter",city);const p=await getJson(u,"No he podido consultar el mapa ahora mismo.");return(Array.isArray(p)?p:[]).map(x=>({lat:x.lat,lon:x.lng,display_name:x.address,importance:x.type==="portal"?1:.75,address:{road:x.address,city:x.muni||x.poblacion,town:x.poblacion,municipality:x.muni,county:x.province,postcode:x.postalCode,country_code:"es"}}))},async()=>{const u=new URL("https://photon.komoot.io/api/");u.searchParams.set("q",`${label}, Espa\u00f1a`);u.searchParams.set("limit","6");const p=await getJson(u,"No he podido consultar el mapa ahora mismo.");return(p.features||[]).map(mapPhoton)},async()=>{const u=new URL("https://nominatim.openstreetmap.org/search");u.searchParams.set("format","jsonv2");u.searchParams.set("countrycodes","es");u.searchParams.set("limit","5");u.searchParams.set("addressdetails","1");u.searchParams.set("accept-language","es");u.searchParams.set("q",`${label}, Espa\u00f1a`);return getJson(u,"No he podido consultar el mapa ahora mismo.")}];let last=null,got=false;for(const src of sources){try{const raw=await src();if(Array.isArray(raw))got=true;const rows=raw.filter(r=>validPoint(r)&&matchesCity(r,city));if(rows.length)return rows[0]}catch(e){last=e}}if(got)throw new Error(`No he encontrado ${label}. Revisa calle, n\u00famero y municipio.`);throw last||new Error("No he podido consultar el mapa ahora mismo.")}
async function route(from,to){const u=new URL(`https://router.project-osrm.org/route/v1/driving/${from.lon},${from.lat};${to.lon},${to.lat}`);u.searchParams.set("overview","false");const p=await getJson(u,"No he podido calcular la ruta por carretera ahora mismo."),r=p.routes?.[0];if(!r)throw new Error("No he encontrado una ruta por carretera.");return r.distance/1000}
async function calculateRoute(){const pickup=fields.pickupAddress.value.trim(),delivery=fields.deliveryAddress.value.trim();if(!pickup||!delivery)return"manual";setStatus("Calculando ruta...");const base=await geocode(fields.baseAddress.value.trim()||"Paseo Independencia 10",fields.baseCity.value.trim()||"Zaragoza"),p=await geocode(pickup,fields.pickupCity.value.trim()),d=await geocode(delivery,fields.deliveryCity.value.trim());fields.emptyKm.value=(await route(base,p)).toFixed(1);fields.loadedKm.value=(await route(p,d)).toFixed(1);return"map"}
async function calculateAndRender(){try{const src=await calculateRoute();const q=calc(read());render(q,src);setStatus(src==="map"?"Estimaci\u00f3n calculada con ruta por carretera.":"Estimaci\u00f3n calculada con kil\u00f3metros manuales.");return q}catch(e){const q=calc(read());render(q,"manual");setStatus(`${e.message||"No he podido conectar con el mapa ahora mismo."} He usado los kil\u00f3metros manuales.`,"error");return q}}
form.addEventListener("submit",e=>{e.preventDefault();calculateAndRender()});
if(reserveBookingButton)reserveBookingButton.addEventListener("click",async()=>{setReserveEnabled(false);setStatus("Preparando reserva...");try{const q=await calculateAndRender();if(!hasApi()){openWA(message(q,"Hola Jairo, quiero reservar este porte:"));setStatus("Solicitud de reserva preparada en WhatsApp.");setReserveEnabled(true);return}const saved=await postRemote("createBooking",payload(q)),s=new Date(saved.booking.startAt),e=new Date(saved.booking.endAt);setStatus(`Reserva guardada: ${range(s,e)}.`);await loadAgenda();await checkAvailability(calc(read()))}catch(e){setStatus(e.message||"No he podido guardar la reserva.","error");await checkAvailability(calc(read()))}});
copyQuoteButton.addEventListener("click",async()=>{if(!lastQuote)render(calc(read()));try{await navigator.clipboard.writeText(message(lastQuote));setStatus("Resumen copiado.")}catch{setStatus("No se pudo copiar autom\u00e1ticamente. Usa el bot\u00f3n de WhatsApp.","error")}});
document.querySelectorAll("input").forEach(i=>{i.addEventListener("input",()=>render(calc(read()),"manual"));i.addEventListener("change",()=>render(calc(read()),"manual"))});
setDefaultDate();render(calc(read()),"manual");loadAgenda();if(window.lucide)window.lucide.createIcons();
